// <auto-generated />
namespace ElfsLeatherStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ELStoreDb07052015 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ELStoreDb07052015));
        
        string IMigrationMetadata.Id
        {
            get { return "201505070433257_ELStoreDb07-05-2015"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
